dotnet-backend/CloudPublishing/Controllers/EmployeeController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using CloudPublishing.Business.Constants;
using CloudPublishing.Business.DTO;
using CloudPublishing.Business.Infrastructure;
using CloudPublishing.Business.Resources.Messages;
using CloudPublishing.Business.Services.Interfaces;
using CloudPublishing.Models.Employees.ViewModels;
using CloudPublishing.Util.Attributes;

namespace CloudPublishing.Controllers
{
    /// <inheritdoc />
    /// <summary>
    ///     Контроллер для работы с сотрудниками издательства
    /// </summary>
    [HandleError]
    public class EmployeeController : Controller
    {
        private readonly IMapper mapper;
        private readonly IEmployeeService service;

        /// <inheritdoc />
        /// <summary>
        ///     Создает экземпляр класса, используя реализации сервиса пользователей
        ///     <see cref="T:CloudPublishing.Business.Services.Interfaces.IEmployeeService" />, сервиса
        ///     аккаунтов <see cref="T:CloudPublishing.Business.Services.Interfaces.IAccountService" /> и маппера
        ///     <see cref="T:AutoMapper.IMapper" /> для отображения сущностей
        /// </summary>
        /// <param name="service">Сервис, предоставляющий доступ функциям по работе с сотрудниками</param>
        /// <param name="mapper">Маппер для отобраения сущностей пользвоателей на модели для представлений</param>
        public EmployeeController(IEmployeeService service, IMapper mapper)
        {
            this.service = service;
            this.mapper = mapper;
        }

        private List<SelectListItem> GetEmployeeTypeList()
        {
            return service.GetEmployeeTypes().Select(x => new SelectListItem
            {
                Value = x.Key,
                Text = x.Value
            }).ToList();
        }

        private List<SelectListItem> GetEmployeeEducationList()
        {
            var list = service.GetEducationList();
            return list.Select(x => new SelectListItem {Text = x.Title, Value = x.Id.ToString()}).ToList();
        }

        /// <summary>
        ///     Метод для получения списка всех сотрудников издательства
        /// </summary>
        /// <returns>Представление со списком сотрудников издательства</returns>
        [HttpGet]
        public ActionResult List()
        {
            var list = service.GetEmployees();

            return View(mapper.Map<IEnumerable<EmployeeDTO>, List<EmployeeViewModel>>(list));
        }

        /// <summary>
        ///     Метод для возврата представления с формой для создания профиля сотрудника
        /// </summary>
        /// <returns>Представление с формой создания</returns>
        [HttpGet]
        [Authorize(Roles = EmployeeRole.ChiefEditor)]
        public ActionResult Create()
        {
            var model = new EmployeeCreateModel
            {
                TypeList = GetEmployeeTypeList(),
                EducationList = GetEmployeeEducationList()
            };
            return View(model);
        }

        /// <summary>
        ///     Метод для создания профиля сотрудника. Реализует проверку данных, введенных пользователем, а также добавление
        ///     данных пользователя в базу, если они валидны
        /// </summary>
        /// <param name="model">Данные с формы создания пользователя</param>
        /// <returns>
        ///     Представление с ошибкой, если
        ///     <see>
        ///         <cref>model</cref>
        ///     </see>
        ///     не проходит валидацию, или переадресация к списку
        ///     сотрудников с сообщением о результате создания
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = EmployeeRole.ChiefEditor)]
        public ActionResult Create(EmployeeCreateModel model)
        {
            if (!ModelState.IsValid)
            {
                model.TypeList = GetEmployeeTypeList();
                model.EducationList = GetEmployeeEducationList();
                return View(model);
            }

            service.CreateEmployee(mapper.Map<EmployeeCreateModel, EmployeeDTO>(model));

            TempData["Message"] = string.Format(Success.AddedEmployee, model.Email);

            return RedirectToAction("List");
        }

        /// <summary>
        ///     Метод для возврата страницы с формой редактирования данных сотрудника
        /// </summary>
        /// <param name="id">Идентификатор пользователя</param>
        /// <returns>Представление с формой редактирования</returns>
        [HttpGet]
        [Authorize(Roles = EmployeeRole.ChiefEditor)]
        [Route("Edit/{id:int}")]
        public ActionResult Edit(int id)
        {
            var employee = service.GetEmployeeById(id);
            if (employee == null)
            {
                TempData["Message"] = Error.NotFoundEmployee;
                return RedirectToAction("List");
            }

            var model = mapper.Map<EmployeeDTO, EmployeeEditModel>(employee);
            model.TypeList = GetEmployeeTypeList();
            model.EducationList = GetEmployeeEducationList();

            return View(model);
        }

        /// <summary>
        ///     Метод для реадктирования данных сотрудника. Реализует валидацию данных, введенных пользователем, а также обновляет
        ///     данные пользователя
        /// </summary>
        /// <param name="model">Данные формы, измененные пользователем</param>
        /// <returns>
        ///     Представление с ошибкой, если
        ///     <see>
        ///         <cref>model</cref>
        ///     </see>
        ///     не проходит валидацию, или переадресация к списку
        ///     сотрудников с сообщением о результате редактирования
        /// </returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = EmployeeRole.ChiefEditor)]
        public ActionResult Edit(EmployeeEditModel model)
        {
            if (!ModelState.IsValid)
            {
                model.TypeList = GetEmployeeTypeList();
                model.EducationList = GetEmployeeEducationList();
                return View(model);
            }

            try
            {
                service.EditEmployee(mapper.Map<EmployeeEditModel, EmployeeDTO>(model));

                TempData["Message"] = string.Format(Success.UpdatedEmployee, model.Email);
            }
            catch (ChiefEditorRoleChangeException e)
            {
                TempData["Message"] = string.Format(Error.UpdateFailedEmployee, e.Message);
            }

            return RedirectToAction("List");
        }

        /// <summary>
        ///     Метод для удаления сотрудника
        /// </summary>
        /// <param name="id">Идентификатор сотрудника</param>
        /// <returns>
        ///     Если пользователя можно удалить, возвращается JSON-объект с сообщением об успешном удалении и соответствующим
        ///     флагом, иначе JSON-объект с флагом об ошибке удаления и сообщением о причине ошибки
        /// </returns>
        [HttpPost]
        [Authorize(Roles = EmployeeRole.ChiefEditor)]
        public ActionResult Delete(int id)
        {
            try
            {
                service.DeleteEmployee(id);
            }
            catch (ChiefEditorRoleChangeException e)
            {
                return Json(new
                {
                    isSuccessful = false,
                    message = e.Message
                }, JsonRequestBehavior.AllowGet);
            }

            return Json(new
            {
                isSuccessful = true,
                message = Success.DeletedEmployee
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

dotnet-backend/CloudPublishing/Controllers/PublishingController.cs
using AutoMapper;
using CloudPublishing.Business.DTO;
using CloudPublishing.Business.Services.Interfaces;
using CloudPublishing.Models.Publishings.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CloudPublishing.Controllers
{
    public class PublishingController : Controller
    {
        private IPublishingService publishingService;
        private IMapper mapper;

        public PublishingController(IPublishingService publishingService, IMapper mapper)
        {
            this.publishingService = publishingService;
            this.mapper = mapper;
        }

        public ActionResult List()
        {
            IEnumerable<PublishingTableViewModel> publishings = mapper
                .Map<IEnumerable<PublishingTableViewModel>>(publishingService.GetPublishings());
            return View(publishings);
        }

        public ActionResult Create()
        {
            PublishingCreateViewModel publishingViewModel = new PublishingCreateViewModel
            {
                Publishing = new PublishingViewModel(),

                AvailableTopics = mapper
                    .Map<IEnumerable<TopicViewModel>>(publishingService.GetTopics()),

                AvailableJournalists = mapper
                    .Map<IEnumerable<PublishingEmployeeViewModel>>(publishingService.GetJournalists()),

                AvailableEditors = mapper
                    .Map<IEnumerable<PublishingEmployeeViewModel>>(publishingService.GetEditors())
            };
            return View(publishingViewModel);
        }

        [HttpPost]
        public ActionResult Create(PublishingViewModel publishing)
        {
            // TODO: Валидация нового журнала
            var publishingDTO = mapper.Map<PublishingDTO>(publishing);
            publishingService.CreatePublishing(publishingDTO);
            return RedirectToAction("List");
        }

        public ActionResult Edit(int id)
        {
            PublishingDTO publishing = publishingService.GetPublishing(id);
            if (publishing == null)
            {
                return null;
            }

            PublishingEditViewModel editViewModel = new PublishingEditViewModel
            {
                Publishing = mapper.Map<PublishingViewModel>(publishing),

                AvailableTopics = mapper
                    .Map<IEnumerable<TopicViewModel>>(publishingService.GetTopicsNotInPublishing(id)),

                TopicsAtPublishing = mapper
                    .Map<IEnumerable<TopicViewModel>>(publishing.Topics),

                EditorsAtPublishing = mapper
                    .Map<IEnumerable<PublishingEmployeeViewModel>>(publishing.Editors),

                JournalistsAtPublishing = mapper
                    .Map<IEnumerable<PublishingEmployeeViewModel>>(publishing.Journalists),

                AvailableEditors = mapper
                    .Map<IEnumerable<PublishingEmployeeViewModel>>(publishingService.GetEditorsNotInPublishing(id)),

                AvailableJournalists = mapper
                    .Map<IEnumerable<PublishingEmployeeViewModel>>(publishingService.GetJournalistsNotInPublishing(id)),
            };

            return View(editViewModel);
        }

        [HttpPost]
        public ActionResult Edit(PublishingViewModel publishing)
        {
            // TODO: Валидация редактированного журнала
            PublishingDTO publishingDTO = mapper.Map<PublishingDTO>(publishing);
            publishingService.UpdatePublishing(publishingDTO);
            return RedirectToAction("List");
        }

        public ActionResult Delete(int id)
        {
            publishingService.DeletePublishing(id);
            return RedirectToAction("List");
        }
    }
}

dotnet-backend/CloudPublishing/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Cloud <i class="fas fa-cloud-sun"></i> Publishing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="employeeDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                        Сотрудники
                    </a>
                    <div class="dropdown-menu" aria-labelledby="employeeDropdown">
                        @Html.ActionLink("Список сотрудников", "List", "Employee", null, new { @class = "dropdown-item" })
                        @if (User.Identity.IsAuthenticated && User.IsInRole("ChiefEditor"))
                        {
                            @Html.ActionLink("Добавить сотрудника", "Create", "Employee", null, new { @class = "dropdown-item" })
                        }
                    </div>
                </li>
                @if (User.Identity.IsAuthenticated && User.IsInRole("ChiefEditor"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="employeeDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                            Журналы
                        </a>
                        <div class="dropdown-menu" aria-labelledby="employeeDropdown">
                            @Html.ActionLink("Список журналов", "List", "Publishing", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Добавить журнал", "Create", "Publishing", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
                @if (User.Identity.IsAuthenticated && (User.IsInRole("ChiefEditor") || User.IsInRole("Editor")))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="employeeDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                            Рецензии
                        </a>
                        <div class="dropdown-menu" aria-labelledby="employeeDropdown">
                            @Html.ActionLink("Список рецензий", "Index", "Review", null, new { @class = "dropdown-item" })
                            @Html.ActionLink("Добавить рецензию", "Create", "Review", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
            </ul>
            <ul class="navbar-nav my-lg-0">
                @if (!User.Identity.IsAuthenticated)
                {
                    <li class="nav-item active">
                        @Html.ActionLink("Авторизация", "LogIn", "Account", null, new { @class = "nav-link" })
                    </li>
                }
                else
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                            @User.Identity.Name
                        </a>
                        <div class="dropdown-menu" aria-labelledby="userDropdown">
                            @Html.ActionLink("Выход", "LogOut", "Account", null, new { @class = "dropdown-item" })
                        </div>
                    </li>
                }
            </ul>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr/>
        <footer>
            <p>&copy; @DateTime.Now.Year - Cloud Publishing</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/libs")
    @RenderSection("scripts", false)
</body>
</html>